@startuml
interface io.github.super_auto_pets.interfaces.GameUnit {
}
class io.github.super_auto_pets.android.AndroidLauncher {
}
class io.github.super_auto_pets.models.Sprite {
}
class io.github.super_auto_pets.controller.BattleController {
}
class io.github.super_auto_pets.models.Battle {
}
class io.github.super_auto_pets.android.EnterNameScreen {
}
class io.github.super_auto_pets.firebase.FirebaseHighscoreService {
}
class io.github.super_auto_pets.factories.SpriteFactory$Companion {
}
class io.github.super_auto_pets.factories.SpriteFactory {
}
class io.github.super_auto_pets.controller.ShopController {
}
class io.github.super_auto_pets.firebase.HighscoreManager {
}
interface io.github.super_auto_pets.interfaces.HighscoreService {
}
class io.github.super_auto_pets.android.Main {
}
class io.github.super_auto_pets.android.EditScreen$Companion {
}
class io.github.super_auto_pets.android.EditScreen$DragPayload {
}
class io.github.super_auto_pets.android.EditScreen {
}
class io.github.super_auto_pets.android.TutorialScreen$Companion {
}
class io.github.super_auto_pets.android.TutorialScreen {
}
class io.github.super_auto_pets.android.GameScreen$Companion {
}
class io.github.super_auto_pets.android.GameScreen {
}
class io.github.super_auto_pets.utilities.JsonParser {
}
class io.github.super_auto_pets.controller.AttackEvent {
}
class io.github.super_auto_pets.models.Shop {
}
class io.github.super_auto_pets.models.Item {
}
class io.github.super_auto_pets.models.Player {
}
class io.github.super_auto_pets.models.Team {
}
enum io.github.super_auto_pets.controller.GameMode {
}
class io.github.super_auto_pets.android.MainMenuScreen$Companion {
}
class io.github.super_auto_pets.android.MainMenuScreen {
}
class io.github.super_auto_pets.models.Empty {
}
class io.github.super_auto_pets.firebase.HighscoreEntry {
}
class io.github.super_auto_pets.controller.PlayerController {
}
class io.github.super_auto_pets.main.Main {
}
class io.github.super_auto_pets.main.null {
}
enum io.github.super_auto_pets.controller.BuildPhase {
}
interface io.github.super_auto_pets.interfaces.ISprite {
}
class io.github.super_auto_pets.managers.PlayerManager {
}
class io.github.super_auto_pets.factories.ItemFactory$Companion {
}
class io.github.super_auto_pets.factories.ItemFactory {
}
class io.github.super_auto_pets.android.HighscoreScreen$Companion {
}
class io.github.super_auto_pets.android.HighscoreScreen {
}


com.badlogic.gdx.backends.android.AndroidApplication <|-- io.github.super_auto_pets.android.AndroidLauncher
io.github.super_auto_pets.interfaces.ISprite <|.. io.github.super_auto_pets.models.Sprite
com.badlogic.gdx.Screen <|.. io.github.super_auto_pets.android.EnterNameScreen
io.github.super_auto_pets.interfaces.HighscoreService <|.. io.github.super_auto_pets.firebase.FirebaseHighscoreService
io.github.super_auto_pets.factories.SpriteFactory +.. io.github.super_auto_pets.factories.SpriteFactory$Companion
com.badlogic.gdx.Game <|-- io.github.super_auto_pets.android.Main
io.github.super_auto_pets.android.EditScreen +.. io.github.super_auto_pets.android.EditScreen$Companion
io.github.super_auto_pets.android.EditScreen +.. io.github.super_auto_pets.android.EditScreen$DragPayload
com.badlogic.gdx.Screen <|.. io.github.super_auto_pets.android.EditScreen
io.github.super_auto_pets.android.TutorialScreen +.. io.github.super_auto_pets.android.TutorialScreen$Companion
com.badlogic.gdx.Screen <|.. io.github.super_auto_pets.android.TutorialScreen
io.github.super_auto_pets.android.GameScreen +.. io.github.super_auto_pets.android.GameScreen$Companion
com.badlogic.gdx.Screen <|.. io.github.super_auto_pets.android.GameScreen
io.github.super_auto_pets.interfaces.GameUnit <|.. io.github.super_auto_pets.models.Item
io.github.super_auto_pets.android.MainMenuScreen +.. io.github.super_auto_pets.android.MainMenuScreen$Companion
com.badlogic.gdx.Screen <|.. io.github.super_auto_pets.android.MainMenuScreen
io.github.super_auto_pets.interfaces.GameUnit <|.. io.github.super_auto_pets.models.Empty
com.badlogic.gdx.ApplicationAdapter <|-- io.github.super_auto_pets.main.Main
io.github.super_auto_pets.main.HighscoreService <|.. io.github.super_auto_pets.main.null
io.github.super_auto_pets.interfaces.GameUnit <|.. io.github.super_auto_pets.interfaces.ISprite
io.github.super_auto_pets.factories.ItemFactory +.. io.github.super_auto_pets.factories.ItemFactory$Companion
io.github.super_auto_pets.android.HighscoreScreen +.. io.github.super_auto_pets.android.HighscoreScreen$Companion
com.badlogic.gdx.Screen <|.. io.github.super_auto_pets.android.HighscoreScreen
@enduml